<a href="https://colab.research.google.com/github/AhmadAghaebrahimian/UZH-BIO390/blob/master/SPARQL_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**SPARQL**

1. Prefix declarations: Abbreviating URIs
          PREFIX foo: <http://example.com/resources/>

2. Result clause: Identify what information to return
          SELECT *

3. Dataset definition: Which RDF graph(s) to query
          FROM

4. Query pattern: Specify what to query
          WHERE {
                  ?s ?p ?o .
                }

5. Modifiers, Slicing, Ordering, or Rearranging the results
          ORDER BY ?s


Open Dbpedia Sparql endpoint https://dbpedia.org/sparql

      PREFIX rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      
      SELECT DISTINCT ?concept
      WHERE {
          ?subject rdf:type ?concept .
      } 
      ORDER BY DESC(?concept)
      LIMIT 10
      OFFSET 2


      PREFIX dbp-owl: <http://dbpedia.org/ontology/>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
      
      SELECT DISTINCT ?country ?label 
      WHERE {
        ?country a dbp-owl:Country .        
        ?country rdfs:label ?label .           
        FILTER langMatches(lang(?label),"en")  
        FILTER contains(?label,"land")         
      }

Built-in filter functions

    Logical: !, &&, ||
    Math: +, -, *, /
    Comparison: =, !=, >, <, ...
    SPARQL tests: isURI, isBlank, isLiteral, bound
    SPARQL accessors: str, lang, datatype
    Other: sameTerm, langMatches, regex

Install Sparql Engine

We use Fuseki server for as the Sparql endpoint. You can download it from the following link. Please make sure you have Java installed on your machine.

https://jena.apache.org/download/index.cgi


Download 'apache-jena-fuseki-4.6.1.zip' and unzip it somewhere in your machine

In the terminal where you unzipped the file:

     ./fuseki-server --update --mem /graph

In the browser

    http://localhost:3030/

Get the example files

    http://www.learningsparql.com/2ndeditionexamples/index.html

Upload 'ex002.ttl'
Get Craig's email

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?craigEmail
    WHERE { 
            ab:craig ab:email ?craigEmail . 
          }

Graph traversal
Load ex012.ttl

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?person
    WHERE { 
            ?person ab:homeTel "(229) 276-5135" . 
          } 

Linking

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?first ?last
    WHERE
    {
      ?person ab:homeTel "(229) 276-5135" . 
      ?person ab:firstName ?first . 
      ?person ab:lastName  ?last . 
    }

Integration

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?full_name
    WHERE
    {
      ?person ab:homeTel "(229) 276-5135" . 
      ?person ab:firstName ?first . 
      ?person ab:lastName  ?last . 
      BIND (concat(?first, ' ', ?last) AS ?full_name) .
    }

Multiple conditions

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?first ?last
    WHERE
    {
      ?person ab:homeTel "(229) 276-5135" . 
      ?person ab:firstName ?first . 
      ?person ab:lastName  ?last . 
    }

Shortcut ;

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?first ?last
    WHERE
    {
      ?person ab:homeTel "(229) 276-5135" ; 
              ab:firstName ?first ; 
              ab:lastName  ?last . 
    }


    PREFIX ab: <http://learningsparql.com/ns/addressbook#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/> 

    SELECT ?name ?homepage
    WHERE
    {
      ?name ab:firstName "John" ;
            foaf:homepage  "<https://first-homepage.com>" ,
                           "<https://second-homepage.com>" .
                            
           
    }


    PREFIX ab: <http://learningsparql.com/ns/addressbook#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
    Prefix xsd: <http://www.w3.org/2001/XMLSchema#>

    SELECT ?name ?last
    WHERE
    {
      ?name ab:firstName "JÃ¼rgen"@de ; 
            foaf:age "32"^^xsd:integer .
           
    }

Optional conditions

Load ex054.ttl

Logical AND

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?first ?last ?workTel ?nick
    WHERE
    {
      ?s  ab:firstName ?first ;
          ab:lastName ?last ;
          ab:workTel ?workTel ; 
          ab:nick ?nick . 

    }

Logical OR

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?first ?last ?workTel ?nick
    WHERE
    {
      ?s ab:firstName ?first ;
         ab:lastName ?last .
      OPTIONAL { ?s ab:workTel ?workTel . }
      OPTIONAL { ?s ab:nick ?nick .  }

    }

Negation

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?first ?last 
    WHERE
    {
      ?s ab:firstName ?first ;
        ab:lastName ?last .
      FILTER NOT EXISTS { ?s ab:workTel ?workNum }
    }


Bind and Filter

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    Prefix xsd: <http://www.w3.org/2001/XMLSchema#>

    SELECT ?first ?last 
    WHERE
    {
      ?s ab:firstName ?first ;
         ab:lastName ?last ;
         foaf:age ?age .

      FILTER (!bound(?workNum))
      FILTER (xsd:integer(?age) > 30)
    }

 

Minus

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
    SELECT ?first ?last 
    WHERE
    {
      ?s ab:firstName ?first ;
         ab:lastName ?last .
      MINUS { ?s ab:workTel ?workNum }
    }

Limit search results

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
    SELECT ?first ?last 
    WHERE
    {
      ?s ab:firstName ?first ;
         ab:lastName ?last .
    }
    VALUES ?first {"Richard" "Cindy"}
 

Graph traversal

    PREFIX ab: <http://learningsparql.com/ns/addressbook#>
    PREFIX foaf: <http://xmlns.com/foaf/0.1/>  
    SELECT ?friend 
    WHERE
    {
      ?s ab:firstName "John" ;
         foaf:knows+ ?friend.
    }
Other regex include: | ! * ?

Multiple graphs

Load ex072.ttl, ex073.ttl, ex368.ttl

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?last ?first ?courseName 
    WHERE
        {
          ?s ab:firstName ?first ;
            ab:lastName ?last ;
            ab:takingCourse ?course . 

          ?course ab:courseTitle ?courseName . 
        }

Deduplicate

    PREFIX ab: <http://learningsparql.com/ns/addressbook#>

    SELECT DISTINCT ?first ?last 
    WHERE
        {
          ?s ab:takingCourse ?class ;
            ab:firstName ?first ;
            ab:lastName ?last . 
        }

Union

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 
    PREFIX d:  <http://learningsparql.com/ns/data#> 

    SELECT * 
    WHERE
    {
          { ?person ab:firstName ?first ; 
                    ab:lastName ?last . }

          UNION

          { ?course ab:courseTitle ?courseName . }

    }

Result modifiers

Load ex145.ttl

    PREFIX e: <http://learningsparql.com/ns/expenses#>

    SELECT ?description ?date ?amount
    WHERE
    {
      ?meal e:description ?description ;
            e:date ?date ;
            e:amount ?amount . 
    }

    ORDER BY ?amount
    LIMIT 1

Similarly

    PREFIX e: <http://learningsparql.com/ns/expenses#> 

    SELECT (MAX(?amount) as ?maxAmount) 
    WHERE { ?meal e:amount ?amount . }

Counting, Summing, Averaging, Max and minimizing

    PREFIX e: <http://learningsparql.com/ns/expenses#>

    SELECT (COUNT(?amount) AS ?count)
    WHERE
        {
          ?meal e:description ?description ;
          e:date ?date ;
          e:amount ?amount . 
        }

Aggregation

    PREFIX e: <http://learningsparql.com/ns/expenses#>

    SELECT (SUM(?amount) as ?Sum)
    WHERE
        {
          ?meal e:description ?description ;
          e:date ?date ;
          e:amount ?amount . 
        }
    GROUP BY ?description
    # HAVING (?Sum < 40)

Subquery

    PREFIX ab: <http://learningsparql.com/ns/addressbook#>

    SELECT ?lastName ?courseName 
    WHERE
    {
      {
        SELECT ?lastName 
        WHERE { ?student ab:lastName ?lastName . }
      }

      {
        SELECT ?courseName 
        WHERE { ?course ab:courseTitle ?courseName . }
      }

    }

Blank node
ex041.ttl


    @prefix ab: <http://learningsparql.com/ns/addressbook#> .

    ab:i0432 ab:firstName    "Richard" ;
            ab:lastName      "Mutt" ;
            ab:homeTel       "(229) 276-5135" ;
            ab:email         "richard49@hotmail.com" ;
            ab:postalCode    "49345" ;
            ab:city          "Springfield" ;
            ab:streetAddress "32 Main St." ;
            ab:region        "Connecticut" . 



    @prefix ab: <http://learningsparql.com/ns/addressbook#> .

    ab:i0432 ab:firstName    "Richard" ;
            ab:lastName      "Mutt" ;
            ab:homeTel       "(229) 276-5135" ;
            ab:email         "richard49@hotmail.com" ;
            ab:address       _:b1 .

    _:b1    ab:postalCode    "49345" ;
            ab:city          "Springfield" ;
            ab:streetAddress "32 Main St." ;
            ab:region        "Connecticut" . 

Result?

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?addressVal
    WHERE { ?s ab:address ?addressVal }

-

    PREFIX ab: <http://learningsparql.com/ns/addressbook#> 

    SELECT ?firstName ?lastName ?streetAddress ?city ?region ?postalCode
    WHERE 
    { 
      ?s ab:firstName ?firstName ;
        ab:lastName ?lastName ;
        ab:address ?address . 

      ?address ab:postalCode ?postalCode ;
              ab:city ?city ;
              ab:streetAddress ?streetAddress ;
              ab:region ?region . 
    }

Remote endpoint

    SELECT ?p ?o 
    WHERE
    {
      SERVICE <http://DBpedia.org/sparql>
      { SELECT ?p ?o 
        WHERE { <http://dbpedia.org/resource/Joseph_Hocking> ?p ?o . }
      }
    }


Named Graph

    PREFIX ab: <http://learningsparql.com/ns/addressbook#>

    SELECT ?lname ?courseName 
    FROM <ex069.ttl> 
    FROM NAMED <ex125.ttl>
    FROM NAMED <ex122.ttl> 

    WHERE
    {
      { ?student ab:lastName ?lname }
      UNION
      { GRAPH <ex125.ttl> { ?course ab:courseTitle ?courseName } }
    }

Open BioPortal Sparql endpoint: http://sparql.bioontology.org/

    skos:prefLabel vs. rdfs:label (PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>)

      PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
      PREFIX snomed-term: <http://purl.bioontology.org/ontology/SNOMEDCT/>

      SELECT DISTINCT *
      FROM <http://bioportal.bioontology.org/ontologies/SNOMEDCT>
      FROM <http://bioportal.bioontology.org/ontologies/globals>
      WHERE {
          ?x skos:prefLabel ?label .
          FILTER (CONTAINS ( UCASE(str(?label)), "MELANOMA") )
      }

Open UniProt Sparql endpoint: https://sparql.uniprot.org/

    Shortest comments for a UniProtKB Natural Variant Annotation

      PREFIX up: <http://purl.uniprot.org/core/>
      PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

      SELECT ?annotation ?comment
      WHERE {
        ?annotation a up:Natural_Variant_Annotation ;
                    rdfs:comment ?comment . 
      } 
      ORDER BY (STRLEN(?comment))

    
    
    Find how often an article in pubmed was used in an evidence tag

      PREFIX up: <http://purl.uniprot.org/core/>
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      
      SELECT ?source (COUNT(?attribution) AS ?attribitions)
      WHERE
      {
        ?protein  a up:Protein ;
                  up:annotation ?annotation .
        ?linkToEvidence rdf:object ?annotation ;
                        up:attribution ?attribution .
        ?attribution up:source ?source .
        ?source a up:Journal_Citation .
      } 
      GROUP BY ?source ORDER BY DESC(COUNT(?attribution))

Open NeXtProt Sparql endpoint: https://snorql.nextprot.org/
 
 
    List Lipoproteins

    SELECT distinct ?protein 
    WHERE {
      ?protein :isoform ?iso.
      ?iso :uniprotKeyword / :term cv:KW-0449.
    }

Other usefull Endpoints
 
	â¢ EBI European Bioinformatics Institute:
		- BioSamples, BioModels, ChEMBL, Expression Atlas, Reactome, Ensembl
		- https://www.ebi.ac.uk/rdf/services/sparql

	â¢ NCBI National Center for Biotechnology Information:
		- PubChemRDF (rdf only, no SPARQL endpoint)
		- https://pubchemdocs.ncbi.nlm.nih.gov/rdf

	â¢ SIB:
		- http://sparql-playground.sib.swiss/